name: 'growth_analytics'
version: '1.0.0'
config-version: 2

profile: 'growth_analytics'

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']
clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  growth_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  growth_analytics:
    +quote_columns: false
    crm_pipeline:
      +column_types:
        amount: numeric
    paid_ads:
      +column_types:
        cost: numeric
